In [ ]:
import torch

In [ ]:
torch.cuda.is_available()
# torch.cuda.device_count()
# torch.cuda.current_device()
# torch.cuda.device(0)
# torch.cuda.get_device_name(0)

True

In [ ]:
device = torch.device("cuda")
print(device)

cuda


In [ ]:
#Creating a new tensor on gpu
torch.rand((2,3), device=device)

tensor([[0.4023, 0.1210, 0.0942],
        [0.7403, 0.8190, 0.4046]], device='cuda:0')

In [ ]:
#moving an existing tensor to gpu
a = torch.rand((2,3))
print(a)

tensor([[0.0648, 0.2109, 0.2064],
        [0.9164, 0.0423, 0.0369]])


In [ ]:
b = a.to(device)
print(b)

tensor([[0.0648, 0.2109, 0.2064],
        [0.9164, 0.0423, 0.0369]], device='cuda:0')


In [ ]:
b+5

tensor([[5.0648, 5.2109, 5.2064],
        [5.9164, 5.0423, 5.0369]], device='cuda:0')

###Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#Reshape
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b= torch.rand(2,3,4)
print(b)

tensor([[[0.7989, 0.1945, 0.1776, 0.5944],
         [0.7028, 0.3228, 0.8148, 0.2550],
         [0.8975, 0.5412, 0.2433, 0.5968]],

        [[0.5107, 0.4084, 0.9789, 0.1219],
         [0.5297, 0.6659, 0.0664, 0.0752],
         [0.1959, 0.8254, 0.7394, 0.6591]]])


In [ ]:
print(b.permute(2,0,1))
print(b.permute(2,0,1).shape)

tensor([[[0.7989, 0.7028, 0.8975],
         [0.5107, 0.5297, 0.1959]],

        [[0.1945, 0.3228, 0.5412],
         [0.4084, 0.6659, 0.8254]],

        [[0.1776, 0.8148, 0.2433],
         [0.9789, 0.0664, 0.7394]],

        [[0.5944, 0.2550, 0.5968],
         [0.1219, 0.0752, 0.6591]]])
torch.Size([4, 2, 3])


In [ ]:
b.shape

torch.Size([2, 3, 4])

In [ ]:
#Unsqueeze
#image size
c = torch.rand(226,226,3)
print(c.shape)
print(c)

print(c.unsqueeze(0).shape)

torch.Size([226, 226, 3])
tensor([[[0.5890, 0.0054, 0.2275],
         [0.8630, 0.9619, 0.9208],
         [0.2361, 0.5177, 0.8590],
         ...,
         [0.3534, 0.5712, 0.7733],
         [0.1967, 0.6014, 0.1136],
         [0.9423, 0.3798, 0.6205]],

        [[0.2651, 0.6451, 0.4064],
         [0.9523, 0.0196, 0.0508],
         [0.5382, 0.2704, 0.5294],
         ...,
         [0.3737, 0.0126, 0.0766],
         [0.3482, 0.3738, 0.5218],
         [0.8942, 0.4295, 0.2168]],

        [[0.0479, 0.4040, 0.1597],
         [0.6857, 0.0704, 0.7267],
         [0.5574, 0.1993, 0.8620],
         ...,
         [0.9118, 0.5426, 0.0896],
         [0.4980, 0.4731, 0.8756],
         [0.2820, 0.9738, 0.0310]],

        ...,

        [[0.6801, 0.1471, 0.1044],
         [0.2990, 0.2080, 0.7497],
         [0.4689, 0.2277, 0.9172],
         ...,
         [0.6511, 0.6160, 0.9225],
         [0.9424, 0.1354, 0.2204],
         [0.0870, 0.0272, 0.3330]],

        [[0.9065, 0.6533, 0.5445],
         [0.5986, 0.7

In [ ]:
print(c.shape)
print(c.unsqueeze(0).shape)
print(c.unsqueeze(1).shape)
print(c.unsqueeze(2).shape)
print(c.unsqueeze(3).shape)

torch.Size([226, 226, 3])
torch.Size([1, 226, 226, 3])
torch.Size([226, 1, 226, 3])
torch.Size([226, 226, 1, 3])
torch.Size([226, 226, 3, 1])


In [ ]:
#squeeze
d = torch.rand(1,20)
print(d.shape)
print(d)
print(d.squeeze(0).shape)
print(d.squeeze(0))

torch.Size([1, 20])
tensor([[0.3003, 0.4551, 0.9095, 0.4769, 0.0984, 0.0522, 0.4005, 0.4367, 0.5239,
         0.7852, 0.4794, 0.2820, 0.4376, 0.0591, 0.9865, 0.8754, 0.5119, 0.0244,
         0.6260, 0.2282]])
torch.Size([20])
tensor([0.3003, 0.4551, 0.9095, 0.4769, 0.0984, 0.0522, 0.4005, 0.4367, 0.5239,
        0.7852, 0.4794, 0.2820, 0.4376, 0.0591, 0.9865, 0.8754, 0.5119, 0.0244,
        0.6260, 0.2282])


###Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
print(a)
b = a.numpy()
print(b)
print(type(b))
print(type(a))

tensor([1, 2, 3])
[1 2 3]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [ ]:
print(b)
c=torch.from_numpy(b)
print(type(c))

[1 2 3]
<class 'torch.Tensor'>
