In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print('GPU is available!')
    print(torch.cuda.get_device_name(0))
    print(torch.cuda.device_count())
else:
    print("GPU isn't available. Using CPU")

GPU is available!
Tesla T4
1


**Creting a Tensor**

In [ ]:
 ## using empty

 a = torch.empty(2,3)  #creating space in memory alocating default value.
 a

tensor([[-9.4763e-03,  3.2736e-41, -9.7957e-03],
        [ 3.2736e-41,  1.0650e-43,  8.7861e-43]])

In [ ]:
## check type
type(a)

torch.Tensor

In [ ]:
## using zeros
torch.zeros(2,3)        #creating a tensor 2x3 intialize with zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
## using ones
torch.ones(2,3)       #creating a tensor 2x3 intialize with one

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
## using rand
torch.rand(2,3)       #creating a tensor 2x3 intialize with random values in between 0 to 1

tensor([[0.5540, 0.9428, 0.3467],
        [0.4537, 0.2344, 0.7057]])

torch.rand() always create new tensor as it choose randomly. To encounter this problem We need to use seed. If we set a seed, Every time rand wil generate same tensor.

In [ ]:
## Using seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
## using tensor
torch.tensor([[1,2,3],[4,5,6]]) # to create customize tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
## using arange
print("using arange ->", torch.arange(1,10,2))   # creating a 1-D tensor between two numbers. Also you can use step

## using line space
print("using line space ->", torch.linspace(1,10, steps=5)) # creating a 1-d tensor between two numbers which are evenly spaced
print("using line space ->", torch.linspace(1,10, 10))

## using eye
print("using eye ->", torch.eye(5))  # creting identity metrix

## using full
print("using full ->", torch.full((2,3), 5)) # creating a 2x3 tensor with initialize with 5

using arange -> tensor([1, 3, 5, 7, 9])
using line space -> tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
using line space -> tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


**Tensor Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
x.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [ ]:
torch.empty_like(x) #creating a same size of tensor with default value

tensor([[134226063182704, 134226063165904, 134226063182768],
        [134226063166080, 134226063182832, 134226063166256]])

In [ ]:
torch.zeros_like(x) #creating a same size of tensor with zero

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x) #creating a same size of tensor with one

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float16) #creating a same size of tensor with random values

tensor([[0.3726, 0.1445, 0.0220],
        [0.6743, 0.5371, 0.4937]], dtype=torch.float16)

**Tensor Data Types**

In [ ]:
## find data type
x.dtype

torch.int64

In [ ]:
## asign data type
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print(x)
x.dtype

tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.float32

In [ ]:
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype=torch.int8)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int8)

In [ ]:
# using to ()
x.to(torch.int16)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


###Mathetical Operation

**1. Scalar Operation**

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.1842, 0.9704],
        [0.6965, 0.4654]])

In [ ]:
# addition
x1 = x+2
print(x1)
# substraction
x2 =x-2
print(x2)
# multiplication
x3 =x*3
print(x3)
# division
x4 = x/3
print(x4)
# int division
x5 =(x*100)//3
print(x5)
# mod
x6 =((x*100)//3)%2
print(x6)
# power
x7 =x**2
print(x7)

tensor([[2.1842, 2.9704],
        [2.6965, 2.4654]])
tensor([[-1.8158, -1.0296],
        [-1.3035, -1.5346]])
tensor([[0.5526, 2.9112],
        [2.0894, 1.3963]])
tensor([[0.0614, 0.3235],
        [0.2322, 0.1551]])
tensor([[ 6., 32.],
        [23., 15.]])
tensor([[0., 0.],
        [1., 1.]])
tensor([[0.0339, 0.9417],
        [0.4851, 0.2166]])


### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2767, 0.5959, 0.0870],
        [0.6444, 0.2574, 0.9637]])
tensor([[0.4151, 0.8136, 0.3082],
        [0.4601, 0.7358, 0.3938]])


In [ ]:
# add
print(a + b)
# sub
print(a - b)
# multiply
print(a * b)
# division
print(a / b)
# power
print(a ** b)
# mod
print(a % b)

tensor([[0.6918, 1.4095, 0.3952],
        [1.1046, 0.9932, 1.3576]])
tensor([[-0.1384, -0.2177, -0.2212],
        [ 0.1843, -0.4784,  0.5699]])
tensor([[0.1149, 0.4848, 0.0268],
        [0.2965, 0.1894, 0.3796]])
tensor([[0.6667, 0.7324, 0.2822],
        [1.4005, 0.3498, 2.4470]])
tensor([[0.5867, 0.6562, 0.4711],
        [0.8170, 0.3684, 0.9856]])
tensor([[0.2767, 0.5959, 0.0870],
        [0.1843, 0.2574, 0.1761]])


In [ ]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
#absolute value
print(torch.abs(c))

tensor([1, 2, 3, 4])


In [ ]:
#negative
print(torch.neg(c))

tensor([-1,  2, -3,  4])


In [ ]:
d = torch.tensor([1.5, 2.3, 3.9, 4.4])
d

tensor([1.5000, 2.3000, 3.9000, 4.4000])

In [ ]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[9, 1, 5],
        [1, 9, 0]])

In [ ]:
#sum
print(torch.sum(e))
#sum along columns
print(torch.sum(e, dim=0))
#sum along rows
print(torch.sum(e, dim=1))

tensor(25)
tensor([10, 10,  5])
tensor([15, 10])


In [ ]:
#mean
print(torch.mean(e))

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#We need to change the datatype if we want to calculate mean of tensor
e1= e.to(torch.float32)
e1

tensor([[9., 1., 5.],
        [1., 9., 0.]])

In [ ]:
#mean
print(torch.mean(e1))
#mean along columns
print(torch.mean(e1, dim=0))
#mean along rows
print(torch.mean(e1, dim=1))

tensor(4.1667)
tensor([5.0000, 5.0000, 2.5000])
tensor([5.0000, 3.3333])


In [ ]:
#Or we can declare the float datatype at first
e2 = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(e2)
print(e2.dtype)
#mean
print(torch.mean(e2))
#mean along columns
print(torch.mean(e2, dim=0))
#mean along rows
print(torch.mean(e2, dim=1))

tensor([[6., 2., 0.],
        [0., 5., 1.]])
torch.float32
tensor(2.3333)
tensor([3.0000, 3.5000, 0.5000])
tensor([2.6667, 2.0000])


In [ ]:
#median
print(torch.median(e))

tensor(1)


In [ ]:
#max and min
print(torch.max(e))
print(torch.min(e))

tensor(9)
tensor(0)


In [ ]:
#product
print(torch.prod(e))
print(torch.prod(e1))
print(torch.prod(e2))

tensor(0)
tensor(0.)
tensor(0.)


In [ ]:
#standard deviation
print(torch.std(e1))

tensor(4.1191)


In [ ]:
#variance
print(torch.var(e1))

tensor(16.9667)


In [ ]:
#argmax
print(e1)
print(torch.argmax(e1))

tensor([[9., 1., 5.],
        [1., 9., 0.]])
tensor(0)


In [ ]:
#argmin
print(torch.argmin(e1))

tensor(5)


### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 0, 4],
        [0, 5, 5]])
tensor([[7, 8],
        [8, 0],
        [3, 6]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[54, 72],
        [55, 30]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[6, 0],
        [0, 5],
        [4, 5]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 5., 1.],
        [0., 4., 5.],
        [2., 6., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(42.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.0476, -0.8095,  0.5000],
        [ 0.2381, -0.0476,  0.0000],
        [-0.1905,  0.2381,  0.0000]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 9, 6],
        [9, 7, 6]])
tensor([[6, 7, 1],
        [3, 7, 7]])


In [ ]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)
# greater than equal to
print(i >= j)
# less than equal to
print(i <= j)

tensor([[False,  True,  True],
        [ True, False, False]])
tensor([[ True, False, False],
        [False, False,  True]])
tensor([[False, False, False],
        [False,  True, False]])
tensor([[ True,  True,  True],
        [ True, False,  True]])
tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[ True, False, False],
        [False,  True,  True]])


### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 4., 9.],
        [9., 0., 3.]])

In [ ]:
# log
torch.log(k)

tensor([[1.0986, 1.3863, 2.1972],
        [2.1972,   -inf, 1.0986]])

In [ ]:
# exp
torch.exp(k)

tensor([[2.0086e+01, 5.4598e+01, 8.1031e+03],
        [8.1031e+03, 1.0000e+00, 2.0086e+01]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 2.0000, 3.0000],
        [3.0000, 0.0000, 1.7321]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9820, 0.9999],
        [0.9999, 0.5000, 0.9526]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0025, 0.9820, 0.9975],
        [0.9975, 0.0180, 0.0025]])

In [ ]:
# relu
torch.relu(k)

tensor([[3., 4., 9.],
        [9., 0., 3.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0159, 0.6071, 0.9652],
        [0.9782, 0.3862, 0.2941]])
tensor([[0.8335, 0.0523, 0.4105],
        [0.5909, 0.2835, 0.0378]])


In [ ]:
m.add_(n)

tensor([[0.8493, 0.6595, 1.3757],
        [1.5690, 0.6697, 0.3319]])

In [ ]:
m

tensor([[0.8493, 0.6595, 1.3757],
        [1.5690, 0.6697, 0.3319]])

In [ ]:
n

tensor([[0.8335, 0.0523, 0.4105],
        [0.5909, 0.2835, 0.0378]])

In [ ]:
torch.relu(m)

tensor([[0.8493, 0.6595, 1.3757],
        [1.5690, 0.6697, 0.3319]])

In [ ]:
m.relu_()

tensor([[0.8493, 0.6595, 1.3757],
        [1.5690, 0.6697, 0.3319]])

In [ ]:
m

tensor([[0.8493, 0.6595, 1.3757],
        [1.5690, 0.6697, 0.3319]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.4186, 0.1503, 0.9305],
        [0.2746, 0.1763, 0.4919]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.4186, 0.1503, 0.9305],
        [0.2746, 0.1763, 0.4919]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.1503, 0.9305],
        [0.2746, 0.1763, 0.4919]])

In [ ]:
b

tensor([[0.0000, 0.1503, 0.9305],
        [0.2746, 0.1763, 0.4919]])

In [ ]:
id(a)

134192361057712

In [ ]:
id(b)

134192361057712

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.1503, 0.9305],
        [0.2746, 0.1763, 0.4919]])

In [ ]:
b

tensor([[0.0000, 0.1503, 0.9305],
        [0.2746, 0.1763, 0.4919]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.1503,  0.9305],
        [ 0.2746,  0.1763,  0.4919]])

In [ ]:
b

tensor([[0.0000, 0.1503, 0.9305],
        [0.2746, 0.1763, 0.4919]])

In [ ]:
id(a)

134192361057712

In [ ]:
id(b)

134192360973776